language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.6-linux64.tar.xz
  - tar xf arduino-1.8.6-linux64.tar.xz
  - sudo mv arduino-1.8.6 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
env:
  - board=esp32:esp32:nodemcu-32s:FlashFreq=40
install:
  - arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs
  - arduino --install-boards esp32:esp32 --save-prefs
  - arduino --install-library "PubSubClient"
script:
  - arduino --verify --board $board $PWD/main/main.ino 
  - arduino --verify --board $board $PWD/mqtttest/mqtttest.ino
  - arduino --verify --board $board $PWD/webservertest/webservertest.ino
  - arduino --verify --board $board $PWD/settingstest/settingstest.ino
notifications:
  email:
    on_success: change
    on_failure: change
